FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt . 

RUN pip install --no-cache-dir -r requirements.txt 

COPY app.py .
COPY templates /app/templates
COPY static/ /app/static/

EXPOSE 8080

CMD ["python", "app.py"]
